### PR TITLE
Feature selection & Ablation test

### PR DESCRIPTION
**Pull request by xbh0403**
Should we make Confusion Matrix on all of the models or only the best model?

### CODE REVIEW

**Comment by ziqixu091** [comment]
well, i made cms for each of them to have something to put on the report, is it a lot to make for your case?

**Comment by xbh0403** [comment]
> well, i made cms for each of them to have something to put on the report, is it a lot to make for your case?

~18.

**Comment by ziqixu091** [comment]
okay, probably just put the result into a table then for those not important ones, just make one for the best model haha

**Comment by ziqixu091** [comment]
a table of mse and accuracy i mean, could also include mine for comparison

**Comment by xbh0403** [comment]
> okay, probably just put the result into a table then for those not important ones, just make one for the best model haha

Sounds good.

Don't approve it rn. I'll commit the cms in this branch.

**Comment by xbh0403** [comment]
sure

Ziqi Xu ***@***.***>于2023年12月4日 周一15:59写道：

**Review by LilianHeGao — APPROVED** [review]

**Review by LilianHeGao — APPROVED** [review]

**Pull request merged**
